name: Bruno API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bruno-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
      - name: Run Create User API Test
        run: bru run collections/create_user.bru --env environments/ci.bru --reporter-html results.html
      - name: Run Update User API Test
        run: bru run collections/update_user.bru --env environments/ci.bru --reporter-html results.html
      - name: Run Delete User API Test
        run: bru run collections/delete_user.bru --env environments/ci.bru --reporter-html results.html
      - name: Run Get Users API Test
        run: bru run collections/get_users.bru --env environments/ci.bru --reporter-html results.html
