name: Bruno API Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  bruno-api-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Bruno CLI
        run: npm install -g @usebruno/cli
      - name: Run Bruno collection
        run: bru run collections --env environments/ci.bru
